version: "3.9"
services:

  consul:
    container_name: consul
    image: consul
    ports:
      - "8500:8500"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "9000:8080"

  enigmiservicedb:
    image: postgres:latest
    container_name: enigmiServiceDB
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiServiceDB
    ports:
      - "5455:5432"
    volumes:
      - ./enigmiservicedb-data:/var/lib/postgresql/data

  connessioniservicedb:
    image: postgres:latest
    container_name: connessioniServiceDB
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connessioniServiceDB
    ports:
      - "5456:5432"
    volumes:
      - ./connessioniservicedb-data:/var/lib/postgresql/data

  enigmiseguitiservicedb:
    image: postgres:latest
    container_name: enigmiSeguitiServiceDB
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiSeguitiServiceDB
    ports:
      - "5457:5432"
    volumes:
      - ./enigmiseguitiservicedb-data:/var/lib/postgresql/data

  apigateway:
    container_name: apigateway
    image: tibbo93/apigateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - "consul"

  enigmi:
    image: tibbo93/enigmi-service
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - consul
      - enigmiservicedb
      - kafka

  connessioni:
    image: tibbo93/connessioni-service
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - consul
      - connessioniservicedb
      - kafka

  enigmiseguiti:
    image: tibbo93/enigmi-seguiti-service
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - consul
      - enigmiseguitiservicedb
      - kafka

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock