version: "3.9"
services:

  consul:
    container_name: consul
    image: consul
    ports:
      - "8500:8500"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "9000:8080"

  enigmiservicedb:
    image: postgres:latest
    container_name: enigmiServiceDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiServiceDB
    ports:
      - "5455:5432"

  connessioniservicedb:
    image: postgres:latest
    container_name: connessioniServiceDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connessioniServiceDB
    ports:
      - "5456:5432"

  enigmiseguitiservicedb:
    image: postgres:latest
    container_name: enigmiSeguitiServiceDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiSeguitiServiceDB
    ports:
      - "5457:5432"

  apigateway:
    container_name: apigateway
    image: apigateway-service
    build: ./api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - "consul"

  enigmi:
    image: enigmi-service
    container_name: enigmiService
    build: ./enigmi
    restart: unless-stopped
    depends_on:
      - consul
      - enigmiservicedb

  connessioni:
    image: connessioni-service
    container_name: connessioniService
    build: ./connessioni
    restart: unless-stopped
    depends_on:
      - consul
      - connessioniservicedb

  enigmiseguiti:
    image: enigmi-seguiti-service
    container_name: enigmiSeguitiService
    build: ./enigmi-seguiti
    restart: unless-stopped
    depends_on:
      - consul
      - enigmiseguitiservicedb

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.11.121:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #     - KAFKA_CREATE_TOPICS: "restaurant-service-event-channel:4:1,restaurant-service-command-channel:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock