version: "3.9"
services:

  consul:
    container_name: consul
    image: consul
    ports:
      - "8500:8500"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "9000:8080"

  enigmiservicedb:
    image: postgres:latest
    container_name: enigmiServiceDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiServiceDB
    ports:
      - "5455:5432"

  connessioniservicedb:
    image: postgres:latest
    container_name: connessioniServiceDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connessioniServiceDB
    ports:
      - "5456:5432"

  enigmiseguitiservicedb:
    image: postgres:latest
    container_name: enigmiSeguitiServiceDB
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiSeguitiServiceDB
    ports:
      - "5457:5432"