# application.yml 
--- 
spring: 
  application: 
    name: enigmi-seguiti
  cloud:
    consul:
      host: consul
      port: 8500
      discovery: 
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE 
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check? 
        healthCheckCriticalTimeout: 45s
        # consul deve restituire solo servizi che passano l'health check (default=false) 
        queryPassing: true 
    loadbalancer: 
      ribbon.enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://enigmiseguitiservicedb:5432/enigmiSeguitiServiceDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  main:
    # Kafka
    web-application-type: none
  kafka:
    # non so se va bene
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      group-id: ${spring.application.name}


server: 
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8080

# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false

# per kafka
asw:
  edipogram:
    channel:
      in: asw.edipogram.connessioni
