# -*- mode: ruby -*-
# vi: set ft=ruby :

$minikube = <<-'SCRIPT'
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
SCRIPT

$kubectl = <<-'SCRIPT'
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
SCRIPT

$docker = <<-'SCRIPT'
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg lsb-release -y
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
SCRIPT

$edipogram = <<-'SCRIPT'
git clone https://github.com/not-Karot/asw-edipogram.git
cd asw-edipogram/
git checkout kubernetes
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5120"
    vb.cpus = 2
  end
  
config.vm.provision "shell", inline: $kubectl
config.vm.provision "shell", inline: $minikube
config.vm.provision "shell", inline: $docker
config.vm.provision "shell", inline: $edipogram

end
