version: "3.9"
services:

  consul:
    container_name: consul
    image: consul
    restart: unless-stopped
    ports:
      - "8500:8500"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "9000:8080"

  enigmiservicedb:
    image: postgres:latest
    container_name: enigmiServiceDB
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiServiceDB
    ports:
      - "5455:5432"

  connessioniservicedb:
    image: postgres:latest
    container_name: connessioniServiceDB
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connessioniServiceDB
    ports:
      - "5456:5432"

  enigmiseguitiservicedb:
    image: postgres:latest
    container_name: enigmiSeguitiServiceDB
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enigmiSeguitiServiceDB
    ports:
      - "5457:5432"

  apigateway:
    image: apigateway
    build: ../api-gateway
    container_name: apigateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - "consul"

  enigmi:
    image: enigmi-service
    build: ../enigmi
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - consul
      - enigmiservicedb
      - kafka

  connessioni:
    image: connessioni-service
    build: ../connessioni
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - consul
      - connessioniservicedb
      - kafka

  enigmiseguiti:
    image: enigmi-seguiti-service
    build: ../enigmi-seguiti
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - consul
      - enigmiseguitiservicedb
      - kafka

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock