apiVersion: apps/v1
kind: Deployment
metadata:
  name: enigmiservicedb
  namespace: edipogram
spec:
  selector:
    matchLabels:
      app: enigmiservicedb
  template:
    metadata:
      labels:
        app: enigmiservicedb
    spec:
      containers:
        - name: enigmiservicedb
          image: postgres
          ports:
            - name: http
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: enigmiServiceDB

---
apiVersion: v1
kind: Service
metadata:
  name: enigmiservicedb
  labels:
    app: enigmiservicedb
  namespace: edipogram
spec:
  selector:
    app: enigmiservicedb
  ports:
    - protocol: TCP
      port: 5432